"""convert_project_json_to_jsonb

Revision ID: 2f3644472651
Revises: fb254b9beb8d
Create Date: 2026-10-04 21:03:27.684209
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2f3644472651'
down_revision: Union[str, Sequence[str], None] = 'fb254b9beb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creator_profiles', 'onboarding_answers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('generated_assets', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('video_projects', 'scenes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('video_projects', 'captions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('video_projects', 'music',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('video_projects', 'generation_settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_projects', 'generation_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('video_projects', 'music',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('video_projects', 'captions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('video_projects', 'scenes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('generated_assets', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('creator_profiles', 'onboarding_answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
