"""add_project_type_for_library

Revision ID: 45cb23687c79
Revises: 2f3644472651
Create Date: 2026-10-04 21:19:59.351230
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45cb23687c79'
down_revision: Union[str, Sequence[str], None] = '2f3644472651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_projects', sa.Column('project_type', sa.String(length=32), server_default='short', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_projects', 'project_type')
    # ### end Alembic commands ###
