"""add_analytics_events

Revision ID: 94118b7394ea
Revises: bac38115007a
Create Date: 2026-10-04 21:29:20.880440
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94118b7394ea'
down_revision: Union[str, Sequence[str], None] = 'bac38115007a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_subject', sa.String(length=512), server_default='', nullable=False),
    sa.Column('event_name', sa.String(length=32), server_default='', nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_name IN ('signup', 'first_video', 'generated', 'downloaded', 'product_ad', 'ugc_ad', 'paywall_viewed', 'subscription_started', 'subscription_cancelled', 'restore', 'generation_failed')", name='ck_analytics_event_name'),
    sa.ForeignKeyConstraint(['owner_subject'], ['creator_profiles.identity_subject'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_owner_time', 'analytics_events', ['owner_subject', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_owner_time', table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
