"""initial_shortforge_schema

Revision ID: fb254b9beb8d
Revises: 
Create Date: 2026-10-04 21:01:35.513796
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb254b9beb8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_profiles',
    sa.Column('identity_subject', sa.String(length=512), server_default='', nullable=False),
    sa.Column('display_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('onboarding_answers', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan', sa.String(length=64), server_default='free', nullable=False),
    sa.Column('monthly_video_allowance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('monthly_videos_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('monthly_videos_reserved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('usage_period_start', sa.Date(), server_default=sa.text("date_trunc('month', timezone('UTC', CURRENT_TIMESTAMP))::date"), nullable=False),
    sa.Column('usage_period_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("identity_subject <> ''", name='ck_creator_identity_required'),
    sa.CheckConstraint('monthly_video_allowance >= 0', name='ck_creator_allowance_nonnegative'),
    sa.CheckConstraint('monthly_videos_reserved >= 0', name='ck_creator_reservations_nonnegative'),
    sa.CheckConstraint('monthly_videos_used >= 0', name='ck_creator_usage_nonnegative'),
    sa.CheckConstraint('onboarding_step BETWEEN 0 AND 4', name='ck_creator_onboarding_step'),
    sa.CheckConstraint('usage_period_end IS NULL OR usage_period_end > usage_period_start', name='ck_creator_usage_period'),
    sa.PrimaryKeyConstraint('identity_subject')
    )
    op.create_table('video_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_subject', sa.String(length=512), server_default='', nullable=False),
    sa.Column('title', sa.String(length=200), server_default='Untitled short', nullable=False),
    sa.Column('idea', sa.Text(), server_default='', nullable=False),
    sa.Column('style', sa.String(length=64), server_default='', nullable=False),
    sa.Column('target_duration_seconds', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('language', sa.String(length=32), server_default='en', nullable=False),
    sa.Column('aspect_ratio', sa.String(length=16), server_default='9:16', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('status_message', sa.Text(), server_default='', nullable=False),
    sa.Column('generation_stage', sa.String(length=64), server_default='', nullable=False),
    sa.Column('progress_percent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('generation_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('hook', sa.Text(), server_default='', nullable=False),
    sa.Column('script', sa.Text(), server_default='', nullable=False),
    sa.Column('scenes', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('captions', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('music', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('cta', sa.Text(), server_default='', nullable=False),
    sa.Column('voiceover_text', sa.Text(), server_default='', nullable=False),
    sa.Column('generation_settings', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('output_video_url', sa.Text(), server_default='', nullable=False),
    sa.Column('thumbnail_url', sa.Text(), server_default='', nullable=False),
    sa.Column('error_code', sa.String(length=100), server_default='', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('usage_charged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("owner_subject <> ''", name='ck_project_owner_required'),
    sa.CheckConstraint("status IN ('draft', 'queued', 'generating', 'rendering', 'completed', 'failed', 'cancelled')", name='ck_project_status'),
    sa.CheckConstraint('generation_attempts >= 0', name='ck_project_attempts_nonnegative'),
    sa.CheckConstraint('progress_percent BETWEEN 0 AND 100', name='ck_project_progress_range'),
    sa.CheckConstraint('target_duration_seconds > 0', name='ck_project_duration_positive'),
    sa.ForeignKeyConstraint(['owner_subject'], ['creator_profiles.identity_subject'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_owner_created', 'video_projects', ['owner_subject', 'created_at'], unique=False)
    op.create_index('ix_projects_status_updated', 'video_projects', ['status', 'updated_at'], unique=False)
    op.create_table('generated_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('asset_type', sa.String(length=32), server_default='other', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('url', sa.Text(), server_default='', nullable=False),
    sa.Column('mime_type', sa.String(length=128), server_default='', nullable=False),
    sa.Column('sequence_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=100), server_default='', nullable=False),
    sa.Column('provider_asset_id', sa.String(length=512), server_default='', nullable=False),
    sa.Column('prompt', sa.Text(), server_default='', nullable=False),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("asset_type IN ('image', 'video', 'voiceover', 'music', 'captions', 'thumbnail', 'other')", name='ck_asset_type'),
    sa.CheckConstraint("project_id <> ''", name='ck_asset_project_required'),
    sa.CheckConstraint("status IN ('pending', 'generating', 'ready', 'failed')", name='ck_asset_status'),
    sa.CheckConstraint('byte_size IS NULL OR byte_size >= 0', name='ck_asset_size_nonnegative'),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='ck_asset_duration_nonnegative'),
    sa.CheckConstraint('sequence_index >= 0', name='ck_asset_sequence_nonnegative'),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_project_type_sequence', 'generated_assets', ['project_id', 'asset_type', 'sequence_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_project_type_sequence', table_name='generated_assets')
    op.drop_table('generated_assets')
    op.drop_index('ix_projects_status_updated', table_name='video_projects')
    op.drop_index('ix_projects_owner_created', table_name='video_projects')
    op.drop_table('video_projects')
    op.drop_table('creator_profiles')
    # ### end Alembic commands ###
